version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
sphinx:
  configuration: meta-arm-bsp/documentation/corstone1000/conf.py
formats:
  - pdf
python:
  install:
    - requirements: meta-arm-bsp/documentation/requirements.txt
